### ISSUE TITLE
Should probably be 0 by default 

### ISSUE THREAD

**Issue by bensonbits** [sulcgroup/oxdna_analysis_tools#1]
Hi!

These tools are great!

I tried them with a small system and got a crash here, it should probably be 0 by default. 

https://github.com/sulcgroup/oxdna_analysis_tools/blob/fe88192d5744341f961c6d428caf83f4060f371d/UTILS/base.py#L1022

Cheers

Erik

**Comment by ErikPoppleton** [comment]
Thanks for the note.  You are correct that should default to 0 and it has been updated.  That number refers to the reference point for inboxing the system, which needs to be in the center of the structure.  You may need to update this, especially when working with larger origamis.
