### ISSUE TITLE
forces2pairs shows UnboundLocalError

### ISSUE THREAD

**Issue by Prateek1410** [sulcgroup/oxdna_analysis_tools#10]
Greetings,

When I try to invoke forces2pairs script it shows UnboundLocalError. I have attached the screenshot; please have a look. Thank you for your time and consideration. 

Warm Regards
Prateek 
<img width="957" alt="forces2pairs_error" src="https://user-images.githubusercontent.com/73783939/142198430-e6091b68-3fbb-413c-ad51-d9f999dec0a9.png">

**Comment by ErikPoppleton** [comment]
Hi Prateek,

It's working just fine for me.  Can you include your force file, I suspect there's something wrong with its format.

**Comment by Prateek1410** [comment]
Hi Erik

Please have a look at the forces file. 

Regards
Prateek
[external_forces.txt](https://github.com/sulcgroup/oxdna_analysis_tools/files/7560141/external_forces.txt)

**Comment by ErikPoppleton** [comment]
Hi Prateek,
Looks like I wasn't sanitizing inputs very well on that script and it didn't like the tabs in your file.  I have fixed this with version 1.0.7 which is now up on PyPi.  This Git repo will be updated shortly.

**Comment by Prateek1410** [comment]
Thanks so much, Erik; it works now.
