### ISSUE TITLE
Criteria for choosing a particle pair in Output_bonds.py 

### ISSUE THREAD

**Issue by Prateek1410** [sulcgroup/oxdna_analysis_tools#15]
Good day, all!

Regarding the output of the output_bonds script, I wanted to know on what basis two particles are chosen to display their various interacting parameters (such as Hydrogen Bonding energy).  

I ask this because, in certain cases, I don't see records of a particular pair of particles' in all the given frames of a simulation even though they are closely spaced and look to me to be bonded throughout. 

And even if, at certain instances they are not bonded, I'd expect a record stating HB = 0 like it happens in some cases. 

So, how does the script decide which pairs of particle interactions to include in the record for each frame/configuration? 

Thanks a lot for your time and consideration and for these excellent tools! 

Warm Regards
Prateek

**Comment by ErikPoppleton** [comment]
Hi Prateek,

Output_bonds is basically a Python wrapper around the DNAnalysis program which comes with the oxDNA distribution.  We then use the pair_energy observable, which computes the oxDNA potential function for the structure.  If two nucleotides are not interacting, they will not show up in the energy output.  I have not looked deeply into that code, however based on my experiences identifying paired nucleotides, the oxDNA H-bonding potential covers a quite small area and therefore things that you might expect to show up as bonded are in fact not, but just stacked on their neighbors.

**Comment by Prateek1410** [comment]
Hi Erik

By "If two nucleotides are not interacting, they will not show up in the energy output", do you mean that if all the energies given by the different columns are zero, then the code will conclude that they are not interacting and thus, it won't feature them in the output bonds data. Is it like that?

Thanks, 
Prateek

**Comment by ErikPoppleton** [comment]
Hi Prateek,

Yes, that's exactly right.

**Comment by Prateek1410** [comment]
Okay, got it, thanks Erik!
