### ISSUE TITLE
I have some questions about this script: generate_force.py

### ISSUE THREAD

**Issue by HalseyWang** [sulcgroup/oxdna_analysis_tools#17]
Thanks a lot for the help with this script！！！

but when the running structure is very large, this error occurs, how to fix it?

The error is as follows：
python generate_force.py -o external_forces.txt input 1.dat
Traceback (most recent call last):
  File "generate_force.py", line 41, in <module>
    mysystem = r._get_system()
  File "/home/wangyue/Software/oxdna_analysis_tools_old/UTILS/readers.py", line 177, in _get_system
    return self._read(only_strand_ends=only_strand_ends, skip=False)
  File "/home/wangyue/Software/oxdna_analysis_tools_old/UTILS/readers.py", line 123, in _read
    bb = b
UnboundLocalError: local variable 'b' referenced before assignment

**Comment by ErikPoppleton** [comment]
Your command line invocation is incorrect, you also need a configuration file to generate the forces from (run the script with the `-h` flag to see the full list of options and flags) Not sure why that isn’t throwing error, I will have to look into that.

**Comment by HalseyWang** [comment]
I renamed the configuration file to 1.dat, but this error still occurs. My system is a structure similar to an infinite structure, with about 400,000 nucleotides. Is it a problem with the size of the structure?

thanks!!!

**Comment by ErikPoppleton** [comment]
Hi, sorry for the delayed response, I have been travelling and not checking my computer much.  I am not able to reproduce the error, which version of the code are you running?  I notice that in your error trace it says that `r._get_system()` is line 41 of `generate_force`, however when I look at the current code, that function call is on line 43 which suggests to me that you are not using the same version of the code as I am.  Can you please update your local copy and let me know if the error persists?

**Comment by HalseyWang** [comment]
OK, Thank you very much for your reply in your busy schedule, I will try again.
