### ISSUE TITLE
Ouput_bonds script showing an error 

### ISSUE THREAD

**Issue by Prateek1410** [sulcgroup/oxdna_analysis_tools#23]
Hello!

I am running the output bonds script and it shows the following error: 
All spawned, waiting for results
```
WARNING: Overwriting key `trajectory_file' (`MDJohnofTweezer_Salt1_trajectory.dat' to `MDJohnofTweezer_Salt1_trajectory.dat')
WARNING: Overwriting key `trajectory_file' (`MDJohnofTweezer_Salt1_trajectory.dat' to `MDJohnofTweezer_Salt1_trajectory.dat')
WARNING: Overwriting key `trajectory_file' (`MDJohnofTweezer_Salt1_trajectory.dat' to `MDJohnofTweezer_Salt1_trajectory.dat')
WARNING: Overwriting key `trajectory_file' (`MDJohnofTweezer_Salt1_trajectory.dat' to `MDJohnofTweezer_Salt1_trajectory.dat')
WARNING: Overwriting key `trajectory_file' (`MDJohnofTweezer_Salt1_trajectory.dat' to `MDJohnofTweezer_Salt1_trajectory.dat')
WARNING: Overwriting key `trajectory_file' (`MDJohnofTweezer_Salt1_trajectory.dat' to `MDJohnofTweezer_Salt1_trajectory.dat')
WARNING: Overwriting key `trajectory_file' (`MDJohnofTweezer_Salt1_trajectory.dat' to `MDJohnofTweezer_Salt1_trajectory.dat')
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/output_bonds.py", line 26, in compute
    if (not inp["use_average_seq"] or inp.get_bool("use_average_seq")) and "RNA" in inp["interaction_type"]:
oxpy.core.OxDNAError: Key `use_average_seq' not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prateek/.local/bin/oat", line 8, in <module>
    sys.exit(main())
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/entry.py", line 24, in main
    to_call.main()
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/output_bonds.py", line 153, in main
    energies = output_bonds(traj_info, top_info, inputfile, visualize, conversion_factor, ncpus)
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/output_bonds.py", line 97, in output_bonds
    oat_multiprocesser(traj_info.nconfs, ncpus, compute, callback, ctx)
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/UTILS/oat_multiprocesser.py", line 29, in oat_multiprocesser
    callback(i, r.get())
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
oxpy.core.OxDNAError: Key `use_average_seq' not found
```
I added the use_average_seq = 0 parameter to my input file and then reran it. This gave a different error.  (Also, what are those warnings? Should I be worried about those? )

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/output_bonds.py", line 26, in compute
    if (not inp["use_average_seq"] or inp.get_bool("use_average_seq")) and "RNA" in inp["interaction_type"]:
AttributeError: 'oxpy.core.InputFile' object has no attribute 'get_bool'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prateek/.local/bin/oat", line 8, in <module>
    sys.exit(main())
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/entry.py", line 24, in main
    to_call.main()
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/output_bonds.py", line 153, in main
    energies = output_bonds(traj_info, top_info, inputfile, visualize, conversion_factor, ncpus)
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/output_bonds.py", line 97, in output_bonds
    oat_multiprocesser(traj_info.nconfs, ncpus, compute, callback, ctx)
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/UTILS/oat_multiprocesser.py", line 29, in oat_multiprocesser
    callback(i, r.get())
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'oxpy.core.InputFile' object has no attribute 'get_bool'
```

Many thanks for looking into this. 

Warm Regards
Prateek

**Comment by ErikPoppleton** [comment]
Hi Prateek,

we’re still in the middle of moving stuff around (and I really should put this in the README), but you have to be using the joss_submission branch of oxDNA compiled with Python bindings enabled to use the scripts which compute base pairs. There are bindings used which have not yet been merged into the master branch.

**Comment by Prateek1410** [comment]
Hi Erik!

Thanks for the response. Do you mean I should reinstall oxDNA? 

Prateek

**Comment by ErikPoppleton** [comment]
Yes

**Comment by Prateek1410** [comment]
Hey Erik,

I am confused😅. I have reinstalled oxDNA joss submission branch with python bindings. How should I proceed now?

**Comment by ErikPoppleton** [comment]
Sorry for the confusion, while I was asleep the main oxDNA developer finished up the merge, the master oxDNA branch is what you want to install and OAT will also be automatically installed alongside oxpy.

**Comment by Prateek1410** [comment]
Okay, so with this installation, I don't have to separately install oxdna analysis tools and can delete the ones I already have installed, is it?

**Comment by ErikPoppleton** [comment]
Correct.

**Comment by Prateek1410** [comment]
It's still using the older OAT how do I invoke the newly installed ones?

**Comment by Prateek1410** [comment]
Hi Erik,

Thanks for the help. Output_bonds script is working now. But bond_analysis isn't. When I invoke it with help flag it returns the following error: 

```
Traceback (most recent call last):
  File "/home/prateek/.local/bin/oat", line 8, in <module>
    sys.exit(main())
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/entry.py", line 22, in main
    to_call = import_module('oxDNA_analysis_tools.{}'.format(script))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/prateek/.local/lib/python3.8/site-packages/oxDNA_analysis_tools/bond_analysis.py", line 58, in <module>
    def bond_analysis(traj_info:TrajInfo, top_info:TopInfo, pairs:dict[int, int], inputfile:str, ncpus:int=1) -> Tuple[int, int, int, np.ndarray]:
TypeError: 'type' object is not subscriptable
```
I uninstalled the old OAT, then cloned the master branch of oxDNA with python bindings on. Then I ran the make install command in oxpy. 

Warm Regards
Prateek

**Comment by ErikPoppleton** [comment]
Hi Prateek,

That means your Python installation is out of date.  Subscripting types was introduced in Python 3.8.  If updating causes conflicts with other packages, I would suggest creating a virtual environment for oxDNA.

**Comment by Prateek1410** [comment]
Hi Erik,

My python version is 3.8.10. Could it be cause of this error when I call oat config?
```
UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
```
Everything else is fine when I run oat config. 

Regards
Prateek

**Comment by ErikPoppleton** [comment]
Hi Prateek,

My mistake.  It's 3.9 not 3.8.  I just pushed up a new version which correctly specifies the requirements.

Thank you for sending me the errors you get, its very helpful in ironing out these corner cases.

Thanks to your feedback, the [installation documentation](https://lorenzo-rovigatti.github.io/oxDNA/install.html) has been updated.

**Comment by Prateek1410** [comment]
Hi Erik,

I downloaded and installed python 3.10 on my WSL. Also, I have changed the default python3 version to 3.10 from the older 3.8.10. Yet, OAT is using 3.8.10 (when I invoke oat config). How do I make OAT use the newer version? 

I'm glad to be of any help. Thanks to you and your team for these excellent resources. You all are an inspiration. 

Warm Regards
Prateek

**Comment by ErikPoppleton** [comment]
You have to install OAT with Python 3.10. When you run `python —version` Which is your default?  Make sure that 3.10 is your default. If it is, run `python -m pip install ./analysis` From the oxDNA directory. Otherwise you’re going to need to adjust your environments so that WSL is using the right one.

**Comment by Prateek1410** [comment]
When I run `python --version` it gives me the older version but when I run `python3 --version` it gives me the new one. So, should I uninstall OAT and then reinstall using python3 i.e. `python3 -m pip install ./analysis?`

**Comment by ErikPoppleton** [comment]
Yes, that would work. But to save yourself confusion later you should update your symlinks so that `python` and `python3` point to the same place, but up to you.

**Comment by Prateek1410** [comment]
Okay, I shall look into that. So, in that case, I'd have to make `python` and `python3` refer to the new version, uninstall OAT and then reinstall using `python -m pip install ./analysis`. Am I getting it right?

**Comment by ErikPoppleton** [comment]
Yes. Depending on your Numpy version you might need to add `—no-build-isolation`

**Comment by Prateek1410** [comment]
Hi Erik,

I had put off reinstalling OAT using python 3.10 because I didn't immediately need bond_analysis script and others that I required worked fine. But then, today, I noticed that output_bonds script's output file showed t = 0 for all configurations! 

I thought perhaps, using OAT with python 3.10 would solve the problem so I finally got to work: uninstalled OAT, then in the oxDNA directory I ran the `python3 -m pip install ./analysis` command after installing distutils for python 3.10 using `sudo apt install python3.10-distutils` and then updating pip. 

The installation began with _**Defaulting to user installation because normal site-packages is not writeable**_  but then building wheels process failed citing _**compilation terminated.  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1**_
 **_note: This error originates from a subprocess, and is likely not a problem with pip._**
  _**ERROR: Failed building wheel for oxDNA-analysis-tools**_
  **_Building wheel for biopython (setup.py) ... error_**
  **_error: subprocess-exited-with-error_**
  **_× python setup.py bdist_wheel did not run successfully.
  │ exit code: 1_**

(I installed distutils and updated pip cause otherwise, without distutils it showed _**ModuleNotFoundError: No module named 'distutils.util'**_ and before updating pip it showed _**ImportError: cannot import name 'html5lib' from 'pip._vendor'**_.) 

Warm Regards
PRateek

**Comment by ErikPoppleton** [comment]
This is an error installing biopython, not OAT.  Possibly something to do with the permissions issue that pip ran into.  Can you try first installing Biopython with either pip or conda?
