### ISSUE TITLE
Clarification on 'distance.py' Usage: Measuring Distance Between Backbone Particles Or Alternating Nucleotides

### ISSUE THREAD

**Issue by Mehdiasr** [sulcgroup/oxdna_analysis_tools#25]
When we use 'distance.py' to calculate the distance between two particles, we are actually calculating the distance between the backbone particles (sugares) or alternating nucleotides?

**Comment by ErikPoppleton** [comment]
It calculates the distance between particle center-of-mass (the number found in the configuration file).  If you need backbone-backbone or base-base distance, you need to apply a transform to the center-of-mass depending on the exact model you're using. Unfortunately, I don't know of anywhere these are nicely listed, so I'll do it here:

base positions:
`pos_base = com * 0.4 * a1`

DNA2 backbone:
`pos_back = com - (0.34 * a1 + 0.3408 * a2)` 
where a2 is the cross product of the a1 and a3 vectors.

(these are the formulas used for drawing the objects in [oxView](https://github.com/sulcgroup/oxdna-viewer/tree/master/ts/model))

**Comment by ErikPoppleton** [comment]
But also, please open future issues in the [oxDNA repository](https://github.com/lorenzo-rovigatti/oxDNA).  We no longer use this one since it was merged into the main repo.

**Comment by Mehdiasr** [comment]
Thanks alot  for your assistance, I'll open the future issues in the oxDNA repository.
