### ISSUE TITLE
from os import O_NONBLOCK in reader.py 

### ISSUE THREAD

**Issue by bensonbits** [sulcgroup/oxdna_analysis_tools#3]
Hi Guys,

Great tools, 

I try to run the mean structure on a windows machine but get issues with "from os import O_NONBLOCK" , I dont really understand what it does but it seems to be unix only :/ 

Is there some alternative solution to this ?

Cheers

Erik B

**Comment by bensonbits** [comment]
I tried now to comment it out, and it seems to work still

**Comment by ErikPoppleton** [comment]
You're right.  It was an old attempt at reading the same file with multiple processes that didn't seem to work.
