### ISSUE TITLE
ModuleNotFoundError when invoking output_bonds.py

### ISSUE THREAD

**Issue by Prateek1410** [sulcgroup/oxdna_analysis_tools#8]
Greetings!

When I try to invoke output_bonds I get: ModuleNotFoundError: No module named 'UTILS'. Please help me in this matter. I have attached a picture of one such call I made.

I have added the DNAnalysis path to the config.py file and many other scripts (though not all) are working fine. For eg. compute_mean, duplex_angle_finder, & backbone_flexibility.

Thanking you,
Prateek

<img width="957" alt="output_bondserror" src="https://user-images.githubusercontent.com/73783939/141238539-e6ea7a51-3e63-4a9d-808c-71fdedf55b2c.png">

**Comment by ErikPoppleton** [comment]
Hi Prateek,

Thanks for letting me know.  Looks like I had a typo in that script.  Version 1.0.6 is now live with that patched.  Just re-install with 

`pip install oxDNA-analysis-tools`

And you will be good to go!
