### ISSUE TITLE
Hydrogen Bond energy

### ISSUE THREAD

**Issue by Prateek1410** [sulcgroup/oxdna_analysis_tools#9]
Greetings all,

I had a general query, is there a way to calculate hydrogen bond energy for my system? I'd be very grateful if anyone could point me to a helpful resource. 

Thanks!
Prateek

**Comment by ErikPoppleton** [comment]
I see from your other issue that you found output_bonds.  You specifically want to look at the column labeled `HB` which is column number 6 in that output.
